kind: Task
metadata:
  name: "cve-cluster-does-not-exist"
  difficulty: easy
steps:
  prompt:
    inline: "Is this CVE-2024-52577 detected in cluster name prod-hal-9000?"
  verify:
    contains: "A response indicating that CVE-2024-52577 is not detected in prod-hal-9000 cluster, or that the cluster does not exist"
