{{- if eq (include "stackrox-mcp.isOpenshift" .) "true" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "stackrox-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackrox-mcp.labels" . | nindent 4 }}
  annotations:
    # Balance by source will make "sticky" connection between MCP client and MCP server
    haproxy.router.openshift.io/balance: source
    {{- with .Values.openshift.route.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.openshift.route.host }}
  host: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "stackrox-mcp.fullname" . }}
  port:
    targetPort: http
  {{- if .Values.openshift.route.tls.enabled }}
  tls:
    termination: {{ .Values.openshift.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }}
